# repos:
#   - repo: https://github.com/OWASP/nbdefense.git
#     rev: v1.0.0  # Use the correct version or tag
#     hooks:
#       - id: nbdefense
#         name: NBDefense vulnerability scan
#         files: \.ipynb$  # Ensure it scans .ipynb files



repos:
  - repo: local
    hooks:
      - id: nbdefense-scan
        name: NB Defense Scan
        entry: nbdefense scan --path . --settings settings.toml
        language: system
        types: [jupyter]  # This ensures it only scans .ipynb files
        files: \.ipynb$   # Match only .ipynb files
