# NB Defense settings file

# Redact secrets
# Possible values are `PARTIAL`, `ALL`, `HASH`
# `PARTIAL` will show only leading and trailing characters.
# `ALL` will shadow the full secret.
# `HASH` will replace the full secret with its hashed value.

redact_secret = "PARTIAL"

[plugins]

[plugins."nbdefense.plugins.SecretsPlugin"]
enabled = true
block_on_detection = true
[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "SoftlayerDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "StripeDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "SendGridDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "NpmDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "KeywordDetector"
keyword_exclude = ""

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "IbmCosHmacDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "DiscordBotTokenDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "BasicAuthDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "AzureStorageKeyDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "ArtifactoryDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "AWSKeyDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "CloudantDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "GitHubTokenDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "IbmCloudIamDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "JwtTokenDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "MailchimpDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "PrivateKeyDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "SlackDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "SquareOAuthDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "TwilioKeyDetector"

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "Base64HighEntropyString"
limit = 4.5

[[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
name = "HexHighEntropyString"
limit = 3.0

[plugins."nbdefense.plugins.PIIPlugin"]
enabled = true
confidence_threshold = 0.8
block_on_detection = true

[plugins."nbdefense.plugins.PIIPlugin".entities]
US_PASSPORT = true
AU_MEDICARE = true
AU_TFN = true
AU_ACN = true
AU_ABN = true
UK_NHS = true
US_SSN = true
US_ITIN = true
US_DRIVER_LICENSE = true
US_BANK_NUMBER = true
MEDICAL_LICENSE = true
LOCATION = true
PHONE_NUMBER = true
NRP = true
IP_ADDRESS = true
EMAIL_ADDRESS = true
IBAN_CODE = true
CRYPTO = true
CREDIT_CARD = true
PERSON = true

[plugins."nbdefense.plugins.LicenseDependencyFilePlugin"]
enabled = true
accepted_licenses = [
    "Apache License 2.0",
    "Apache Software License",
    "Apache 2.0",
    "Apache-2.0",
    "BSD",
    "BSD License",
    "BSD 3-Clause",
    "BSD-3-Clause",
    "GNU Library or Lesser General Public License (LGPL)",
    "Microsoft Public License",
    "MIT",
    "MIT License",
    "Python Software Foundation License",
    "ISC License (ISCL)",
    "MIT-0"
]


[plugins."nbdefense.plugins.CVEDependencyFilePlugin"]
enabled = true
block_on_critical = true
block_on_high = true
block_on_medium = true      # ✅ added
block_on_low = true         # ✅ added
trivy_binary_path = "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\trivy.exe"





#CVE IDENTIFICATION


# [plugins."nbdefense.plugins.CVEDependencyFilePlugin"]
# enabled = true
# trivy_binary_path = "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\trivy.exe"
# [plugins."nbdefense.plugins.PIIPlugin"]
# enabled = true
# confidence_threshold = 0.9

# [plugins."nbdefense.plugins.PIIPlugin".entities]
# EMAIL_ADDRESS = false
# PHONE_NUMBER = false
# PERSON = false

# [plugins."nbdefense.plugins.SecretsPlugin"]
# enabled = false

# [[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
# name = "AWSKeyDetector"
# [plugins."nbdefense.plugins.LicenseDependencyFilePlugin"]
# enabled = false
# accepted_licenses = ["MIT", "Apache-2.0"]







#CUSTOMIZABLE SCANNING 
# [plugins]

# [plugins."nbdefense.plugins.SecretsPlugin"]
# enabled = true
# redact_secret = "Hash"
# [[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
# name = "StripeDetector"

# [[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
# name = "AWSKeyDetector"


# [plugins."nbdefense.plugins.PIIPlugin"]
# enabled = true
# confidence_threshold = 0.9
# [plugins."nbdefense.plugins.PIIPlugin".entities]
# EMAIL_ADDRESS = true
# PHONE_NUMBER = true
# PERSON = true 
# IP_ADDRESS = true

# [plugins."nbdefense.plugins.LicenseDependencyFilePlugin"]
# enabled = true
# accepted_licenses = ["MIT", "Apache-2.0", "BSD-3-Clause"]

# [plugins."nbdefense.plugins.CVEDependencyFilePlugin"]
# enabled = true
# trivy_binary_path = "C:\\Users\\Santhiya Devi\\Documents\\nbdefense\\trivy.exe"




#[plugins]

#For pii 
# [plugins."nbdefense.plugins.PIIPlugin"]
# enabled = false
# confidence_threshold = 0.6

# [plugins."nbdefense.plugins.PIIPlugin".entities]
# US_PASSPORT = true
# AU_MEDICARE = true
# AU_TFN = true
# AU_ACN = true
# AU_ABN = true
# UK_NHS = true
# US_SSN = true
# US_ITIN = true
# US_DRIVER_LICENSE = true
# US_BANK_NUMBER = true
# MEDICAL_LICENSE = true
# LOCATION = true
# PHONE_NUMBER = true
# NRP = true
# IP_ADDRESS = true
# EMAIL_ADDRESS = true
# IBAN_CODE = true
# CRYPTO = true
# CREDIT_CARD = true
# PERSON = true

# # For secrets
# [plugins."nbdefense.plugins.SecretsPlugin"]
# enabled = false
# redact_secret = "PARTIAL"
# [[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
# name = "AWSKeyDetector"
# [[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
# name = "GitHubTokenDetector"
# [[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
# name = "CloudantDetector"
# [[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
# name = "IbmCloudIamDetector"
# [[plugins."nbdefense.plugins.SecretsPlugin".secrets_plugins]]
# name = "JwtTokenDetector"


# #for License
# [plugins."nbdefense.plugins.LicensePlugin"]
# enabled = false
# [plugins."nbdefense.plugins.LicenseDependencyFilePlugin"]
# enabled = false
# accepted_licenses = ["MIT", "Apache-2.0", "BSD-3-Clause"]


# # #for cveplugin
# [plugins."nbdefense.plugins.CVEPlugin"]
# enabled = true
# [plugins."nbdefense.plugins.CVEDependencyFilePlugin"]
# enabled = true
# trivy_binary_path = "C:\\Users\\santhiya Devi\\Documents\\nbdefense\\trivy.exe"