name: Bandit Security Scan
on:
  push:
    branches:
      - main
jobs:
  bandit-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Bandit
        run: |
          python -m pip install bandit
      - name: Run Bandit scan
        run: bandit -r .
