name: Snyk Security Scan
on:
  push:
    branches:
      - main
jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Snyk
        uses: snyk/actions/setup@v2
      - name: Run Snyk test
        run: snyk test --all-projects
